site_name: DingoPDM
site_url: https://corygrant.github.io/DingoPDM/
use_directory_urls: true
theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode  
repo_url: https://github.com/corygrant/DingoPDM_HW
repo_name: corygrant/DingoPDM
extra:
  generator: false
markdown_extensions:
  - admonition
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg     
nav:
  - Hardware:
    - PCB: 'hardware/pcb.md'
    - Connections: 'hardware/connections.md'
    - Case: 'hardware/case.md'
  - Firmware:
    - Introduction: 'firmware/introduction.md'
    - Design: 'firmware/design.md'
    - Code Style: 'firmware/code-style.md'
  - Software:
    - Introduction: 'software/introduction.md'
    - Functionality: 'software/functionality.md'